[build]
  command = "cd netlify/functions && npm install && cd ../.. && echo 'Build complete'"
  publish = "."

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["@google/generative-ai"]
  node_bundler = "esbuild"